# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels: 
        - major
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - minor
        - enhancement
    - title: Security/Dependency Changes 🛠
      labels:
        - security
        - dependencies
    - title: Other Changes
      labels:
        - "*"
