# configuration file for sourcery.ai
# config reference: https://docs.sourcery.ai/Reference/Configuration/sourcery-yaml/#github

version: '1'  # The schema version of this config file

ignore: # A list of paths or files which Sourcery will ignore.
- .git
- venv
- .venv
- env
- .env
- .tox

rule_settings:
  enable:
  - default
  disable: []  # A list of rule IDs Sourcery will never suggest.
  rule_types:
  - refactoring
  - suggestion
  - comment
  python_version: '3.12.3' # A string specifying the lowest Python version your project supports. Sourcery will not suggest refactorings requiring a higher Python version.

github:
  labels:
  - refactor
  - python
  - priority-low
  ignore_labels:
  - sourcery-ignore
  request_review: mauvehed
  sourcery_branch: sourcery/{base_branch}
