version: '3.8'

services:
  web:
    image: yourip:latest
    container_name: yourip_debug
    ports:
      - "8080:8080"
    environment:
      FLASK_ENV: development
      FLASK_APP: app/main.py
    command: poetry run flask run --host=0.0.0.0 --port=8080
    volumes:
      - .:/app
