# fly.toml app configuration file generated for mvh-yourip on 2024-05-23T18:14:54-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mvh-yourip'
primary_region = 'dfw'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[experimental]
  auto_rollback = true

[build]
  image = 'ghcr.io/mauvehed/yourip:latest'

[deploy]
  strategy = 'rolling'
  max_unavailable = 1.0

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
