name: Publish Docker Image to GHCR

on:
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/publish-docker-image.yml'
  repository_dispatch:
    types: [publish-docker-image]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag'
        required: true
        default: 'nightly'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          TAG="${{ github.event.client_payload.tag || github.event.inputs.tag }}"
          if [ -z "${TAG}" ]; then
            echo "Error: TAG is not defined. Please ensure that the tag is set in your environment variables or input parameters."
            exit 1
          fi
            echo "Tag is not defined"
            exit 1
          fi

          if [ "${TAG}" = "nightly" ]; then
            docker buildx build \
              --tag ghcr.io/${{ github.repository_owner }}/yourip:nightly \
              --push .
          elif [ "${TAG}" = "test" ]; then
            docker buildx build \
              --tag ghcr.io/${{ github.repository_owner }}/yourip:test \
              --push .
          else
            docker buildx build \
              --tag ghcr.io/${{ github.repository_owner }}/yourip:${TAG} \
              --tag ghcr.io/${{ github.repository_owner }}/yourip:latest \
              --push .

      - name: Logout from GHCR
        run: docker logout ghcr.io
