---
name: Stale

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  stale:
    name: 🧹 Clean up stale issues and PRs
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Run stale
        uses: actions/stale@v6
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 45
          days-before-close: 365
          remove-stale-when-updated: true
          stale-issue-label: "stale"
          exempt-issue-labels: "no-stale,help-wanted"
          stale-issue-message: >
            There hasn't been any activity on this issue recently, and in order
            to prioritize active issues, it will be marked as stale.

            Thank you for your contributions!
          stale-pr-label: "stale"
          exempt-pr-labels: "no-stale"
          stale-pr-message: >
            There hasn't been any activity on this pull request recently, and in
            order to prioritize active work, it has been marked as stale.

            Please review any feedback from the project maintainers to ensure they
            are not actively waiting on you for next steps.

            Thank you for your contributions!
